name: Edit and Commit README Every 2 Minutes

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes

jobs:
  edit-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Edit README.md
      run: |
        echo "Random update: $(date)" >> README.md

    - name: Commit changes
      run: |
        git config user.name "rahulrajmehra01"
        git config user.email "rahulrajmehra06@gmail.com"
        git add README.md
        git commit -m "Random update: $(date)" || echo "No changes to commit"
        git push
